/* src/include/autoconf.h.  Generated automatically by configure.  */
/* src/include/autoconf.h.in.  Generated automatically from configure.in by autoheader 2.13.  */
/*

acconfig.h - template used by autoheader to create config.h.in
config.h.in - used by autoconf to create config.h
config.h - created by autoconf; contains defines generated by autoconf

*/

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define.  */
#define gid_t int

/* Define if you have <sys/wait.h> that is POSIX.1 compatible.  */
/* #undef HAVE_SYS_WAIT_H */

/* Define to `long' if <sys/types.h> doesn't define.  */
/* #undef off_t */

/* Define to `int' if <sys/types.h> doesn't define.  */
#define pid_t int

/* Define as the return type of signal handlers (int or void).  */
#define RETSIGTYPE void

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
/* #undef TIME_WITH_SYS_TIME */

/* Define to `int' if <sys/types.h> doesn't define.  */
#define uid_t int

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
/* #undef WORDS_BIGENDIAN */

/* style of gethost*_r functions */
#define GNUSTYLE 1
#define SYSVSTYLE 2
#define BSDSTYLE 3
/* #define GETHOSTBYADDRRSTYLE GNUSTYLE */
/* #define GETHOSTBYNAMERSTYLE GNUSTYLE */

/* style of ctime_r function */
#define POSIXSTYLE 1
#define SOLARISSTYLE 2
#define CTIMERSTYLE POSIXSTYLE

/* Do we have the crypt function ? */
#define HAVE_CRYPT 1

/* Include support for Ascend binary filter attributes */
#define ASCEND_BINARY 1

/* socklen_t is generally 'int' on systems which don't use it */
#define socklen_t int

/* uint8_t should be the canonical 'octet' for network traffic */
typedef unsigned char uint8_t;

/* uint16_t should be the canonical '2 octets' for network traffic */
typedef unsigned short uint16_t;

/* uint32_t should be the canonical 'network integer' */
typedef unsigned long uint32_t;

/* Include SNMP subagent */
/* #undef WITH_SNMP */

/* Define if you have the <ucd-snmp/asn1.h>, <ucd-snmp/snmp_impl.h> and <ucd-snmp/snmp.h> header file.  */
/* #undef HAVE_UCD_SNMP_ASN1_SNMP_SNMPIMPL_H */

/* Define if you have the <asn1.h>, <snmp_impl.h> and <snmp.h> header file.  */
/* #undef HAVE_ASN1_SNMP_SNMPIMPL_H */

/* Define if you have the snmp library (-lsnmp).  */
/* #undef HAVE_LIBSNMP */

/* define this if we have the <regex.h> header file */
#define HAVE_REGEX_H 1

/* define this if we have REG_EXTENDED (from <regex.h>) */
#define HAVE_REG_EXTENDED 1

/* define to something if you don't have ut_xtime in struct utmpx */
#define ut_xtime ut_tv.tv_sec

/* define if you have OSFC2 authentication */
/* #undef OSFC2 */

/* define if you have OSFSIA authentication */
/* #undef OSFSIA */

/* define if you have IP_PKTINFO (Linux) */
/* #undef IP_PKTINFO */

/* define if you want udpfromto */
/* #undef WITH_UDPFROMTO */

/* define if you have openssl/ssl.h */
/* #undef HAVE_OPENSSL_SSL_H */

/* Define if you have the ctime_r function.  */
/* #undef HAVE_CTIME_R */

/* Define if you have the gethostname function.  */
#define HAVE_GETHOSTNAME 1

/* Define if you have the getopt_long function.  */
#define HAVE_GETOPT_LONG 1

/* Define if you have the getusershell function.  */
#define HAVE_GETUSERSHELL 1

/* Define if you have the gmtime_r function.  */
/* #undef HAVE_GMTIME_R */

/* Define if you have the inet_aton function.  */
/* #undef HAVE_INET_ATON */

/* Define if you have the inet_ntop function.  */
/* #undef HAVE_INET_NTOP */

/* Define if you have the inet_pton function.  */
/* #undef HAVE_INET_PTON */

/* Define if you have the initgroups function.  */
/* #undef HAVE_INITGROUPS */

/* Define if you have the localtime_r function.  */
/* #undef HAVE_LOCALTIME_R */

/* Define if you have the lockf function.  */
/* #undef HAVE_LOCKF */

/* Define if you have the pthread_sigmask function.  */
#define HAVE_PTHREAD_SIGMASK 1

/* Define if you have the setlinebuf function.  */
#define HAVE_SETLINEBUF 1

/* Define if you have the setsid function.  */
#define HAVE_SETSID 1

/* Define if you have the setvbuf function.  */
#define HAVE_SETVBUF 1

/* Define if you have the sigaction function.  */
/* #undef HAVE_SIGACTION */

/* Define if you have the sigaction function.  */
#define HAVE_ISASCII 1

/* Define if you have the sigprocmask function.  */
#define HAVE_SIGPROCMASK 1

/* Define if you have the snprintf function.  */
/* #undef HAVE_SNPRINTF */

/* Define if you have the strcasecmp function.  */
#define HAVE_STRCASECMP 1

/* Define if you have the strncasecmp function.  */
#define HAVE_STRNCASECMP 1

/* Define if you have the strsep function.  */
#define HAVE_STRSEP 1

/* Define if you have the strsignal function.  */
#define HAVE_STRSIGNAL 1

/* Define if you have the vsnprintf function.  */
#define HAVE_VSNPRINTF 1

/* Define if you have the <arpa/inet.h> header file.  */
/* #undef HAVE_ARPA_INET_H */

/* Define if you have the <crypt.h> header file.  */
#define HAVE_CRYPT_H 1

/* Define if you have the <dirent.h> header file.  */
#define HAVE_DIRENT_H 1

/* Define if you have the <dlfcn.h> header file.  */
/* #undef HAVE_DLFCN_H */

/* Define if you have the <errno.h> header file.  */
#define HAVE_ERRNO_H 1

/* Define if you have the <fcntl.h> header file.  */
#define HAVE_FCNTL_H 1

/* Define if you have the <getopt.h> header file.  */
#define HAVE_GETOPT_H 1

/* Define if you have the <inttypes.h> header file.  */
/* #undef HAVE_INTTYPES_H */

/* Define if you have the <malloc.h> header file.  */
#define HAVE_MALLOC_H 1

/* Define if you have the <ndir.h> header file.  */
/* #undef HAVE_NDIR_H */

/* Define if you have the <netdb.h> header file.  */
/* #undefe HAVE_NETDB_H */

/* Define if you have the <netinet/in.h> header file.  */
/* #undef HAVE_NETINET_IN_H */

/* Define if you have the <openssl/crypto.h> header file.  */
/* #undef HAVE_OPENSSL_CRYPTO_H */

/* Define if you have the <openssl/engine.h> header file.  */
/* #undef HAVE_OPENSSL_ENGINE_H */

/* Define if you have the <openssl/err.h> header file.  */
/* #undef HAVE_OPENSSL_ERR_H */

/* Define if you have the <openssl/rand.h> header file.  */
/* #undef HAVE_OPENSSL_RAND_H */

/* Define if you have the <prot.h> header file.  */
/* #undef HAVE_PROT_H */

/* Define if you have the <pthread.h> header file.  */
/* #undef HAVE_PTHREAD_H */

/* Define if you have the <resource.h> header file.  */
/* #undef HAVE_RESOURCE_H */

/* Define if you have the <semaphore.h> header file.  */
#define HAVE_SEMAPHORE_H 1

/* Define if you have the <sia.h> header file.  */
/* #undef HAVE_SIA_H */

/* Define if you have the <siad.h> header file.  */
/* #undef HAVE_SIAD_H */

/* Define if you have the <signal.h> header file.  */
#define HAVE_SIGNAL_H 1

/* Define if you have the <stdint.h> header file.  */
/* #undef HAVE_STDINT_H */

/* Define if you have the <stdio.h> header file.  */
#define HAVE_STDIO_H 1

/* Define if you have the <stdio.h> header file.  */
#define HAVE_STRING_H 1

/* Define if you have the <sys/dir.h> header file.  */
/* #undef HAVE_SYS_DIR_H */

/* Define if you have the <sys/fcntl.h> header file.  */
#define HAVE_SYS_FCNTL_H 1

/* Define if you have the <sys/ndir.h> header file.  */
/* #undef HAVE_SYS_NDIR_H */

/* Define if you have the <sys/security.h> header file.  */
/* #undef HAVE_SYS_SECURITY_H */

/* Define if you have the <sys/select.h> header file.  */
/* #undef HAVE_SYS_SELECT_H */

/* Define if you have the <sys/socket.h> header file.  */
/* #undef HAVE_SYS_SOCKET_H */

/* Define if you have the <sys/stat.h> header file.  */
#define HAVE_SYS_STAT_H 1

/* Define if you have the <sys/time.h> header file.  */
/* #undef HAVE_SYS_TIME_H */

/* Define if you have the <sys/types.h> header file.  */
#define HAVE_SYS_TYPES_H 1

/* Define if you have the <syslog.h> header file.  */
/* #undef HAVE_SYSLOG_H */

/* Define if you have the <unistd.h> header file.  */
/* #undef HAVE_UNISTD_H */

/* Define if you have the <utmp.h> header file.  */
#define HAVE_UTMP_H 1

/* Define if you have the <utmpx.h> header file.  */
#define HAVE_UTMPX_H 1

/* Define if you have the nsl library (-lnsl).  */
#define HAVE_LIBNSL 1

/* Define if you have the resolv library (-lresolv).  */
#define HAVE_LIBRESOLV 1

/* Define if you have the socket library (-lsocket).  */
/* #undef HAVE_LIBSOCKET */

/* Some versions of glibc need this defined for pread/pwrite. */
/* #undef _GNU_SOURCE */

#define HAVE_STDLIB_H	1
#define HAVE_STRING_H	1
#define HAVE_CTYPE_H	1
#define HAVE_MALLOC_H	1
#define HAVE_ERRNO_H	1
#define HAVE_ASSERT_H	1
#define HAVE_MEMCPY	1
#define HAVE_MEMMOVE	1

#define LTDL_OBJDIR		"."

#define u_char uint8_t
#define u_short uint16_t
#define u_long uint32_t
#define u_int uint32_t
#define ssize_t size_t
typedef unsigned int error_t;
typedef unsigned short ino_t;
#include <io.h>
#define access			_access
#define R_OK			0
#define LTDL_OBJDIR		"."

#define strncasecmp	_strnicmp
#define strcasecmp	_stricmp
#define vsnprintf	_vsnprintf
#define execl		_execl
#define execv		_execv
#define execve		_execve
#define strdup		_strdup
#define getpid		_getpid
#define unlink		_unlink
#define mkdir(x, y)	_mkdir(x)

#define S_ISREG(x)	(x & _S_IFREG)